apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: orders-api
      app.kubernetes.io/part-of: commerce
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

images:
  - name: orders-api
    newName: ghcr.io/hesbon-osoro/orders-api
    newTag: 1.0.0
